sudo: required
langauge: generic
services:
  - docker


before_install:
  - docker build -t itachi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true itachi/docker-react npm run test
